#pragma once

extern bool chrsounds;
extern bool jmpsounds;
extern bool flysounds;

void PlayHeroesSound(int ID);

enum HeroesSounds {
	CommonSound_DashPanel = 10100,
	CommonSound_Jumping,
	CreamSound_Attack = 10900,
	CreamSound_FlyBegin,
	CreamSound_FlyAttack,
	CreamSound_FlyUp,
	CreamSound_TeamSwap,
	CreamSound_ThatHurts,
	CreamSound_Hurt1,
	CreamSound_Hurt2,
	CreamSound_Trick,
	CreamSound_CheeseGetHim,
	CreamSound_Death,
	CreamSound_LevelUp,
	CreamSound_Win,
	CreamSound_Lose,
	CreamSound_Idle1,
	CreamSound_Idle2,
	RougeSound_Attack = 11000,
	RougeSound_FlyBegin,
	RougeSound_FlyAttack,
	RougeSound_FlyUp,
	RougeSound_TeamSwap,
	RougeSound_ThatHurts,
	RougeSound_Hurt1,
	RougeSound_Hurt2,
	RougeSound_Trick,
	RougeSound_BombAttack,
	RougeSound_Death,
	RougeSound_LevelUp,
	RougeSound_Win,
	RougeSound_Lose,
	RougeSound_Idle1,
	RougeSound_Idle2,
	CharmySound_Attack = 11100,
	CharmySound_FlyBegin,
	CharmySound_FlyAttack,
	CharmySound_Trick,
	CharmySound_TeamSwap,
	CharmySound_ThatHurts,
	CharmySound_Hurt1,
	CharmySound_Hurt2,
	CharmySound_FlyUp,
	CharmySound_DardAttack,
	CharmySound_Death,
	CharmySound_LevelUp,
	CharmySound_Win,
	CharmySound_Lose,
	CharmySound_Idle1,
	CharmySound_Idle2,
	TailsSound_Attack = 11200,
	TailsSound_FlyBegin,
	TailsSound_FlyAttack,
	TailsSound_FlyUp,
	TailsSound_TeamSwap,
	TailsSound_ThatHurts,
	TailsSound_Hurt1,
	TailsSound_Hurt2,
	TailsSound_Trick,
	TailsSound_BombAttack,
	TailsSound_Death,
	TailsSound_LevelUp,
	TailsSound_Win,
	TailsSound_Lose,
	TailsSound_Idle1,
	TailsSound_Idle2
};